// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/3/6 下午10:08:10
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/zhangyalan/echart/echart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyalan/echart/echart/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyalan/echart/echart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyalan/echart/echart/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyalan/echart/echart/plugins/**/*.{js,ts,mjs}","/Users/zhangyalan/echart/echart/composables/**/*.{js,ts,mjs}","/Users/zhangyalan/echart/echart/utils/**/*.{js,ts,mjs}","/Users/zhangyalan/echart/echart/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyalan/echart/echart/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyalan/echart/echart/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/zhangyalan/echart/echart/app.config.{js,ts,mjs}","/Users/zhangyalan/echart/echart/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;